razorpay/i18nify

- jest.config.js
- package.json
- src/modules/currency/__tests__/formatAmount.test.ts
- src/modules/currency/__tests__/getCurrencyList.test.ts
- src/modules/currency/__tests__/getCurrencySymbol.test.ts
- yarn.lock
This PR adds UT for Currency module to the library.
Fixes # (issue)
Additional snippets: [Thread](Paste the thread link here....)
JIRA : https://razorpay.atlassian.net/browse/ATLAS-23
> feat: Add UT's for Currency Module  [ATLAS-23]

- package.json
- rollup.config.mjs
type declaration files exported with esm bundles.
> [feat]: type declarations exported

- .github/CODEOWNERS
Added @tarun-khanna as code owner for now to ensure necessary approval before merging any pull requests. 
| JIRA link              | https://razorpay.atlassian.net/browse/ATLAS-50  |
> Added code owner for pull requests

- src/common/errorBoundary/__tests__/index.test.ts
- src/common/errorBoundary/index.ts
- Added a HOF that wraps utilities and appends extra params before throwing the error to consumers 
| JIRA link              | https://razorpay.atlassian.net/browse/ATLAS-53  |
> [feat]: centralized error boundary added for modules

- .eslintrc.json
- .github/workflows/danger.yml
- dangerfile.js
- scripts/bundle-size-report.js
Added dangerjs in github action pipeline. This action will perform the below operations
- publish bundle size report on PR 
- Enforce PR meets necessary guidelines
Upon crossing the decided threshold, the report might look like below.
| JIRA link              | https://razorpay.atlassian.net/browse/ATLAS-54 |
> [feat]: danger added for bundle size report and good practices

- .github/workflows/coverage.yml
Coverage for master wasn't getting uploaded to codecov. Due to this, the coverage comparison for pull requests wasn't working. 
Added a fix for this issue in the PR. 
> [fix]: coverage action to run on master push

- .changeset/famous-paws-drum.md
- scripts/publishToNpm.js
public access given at the time of npm publish
> public access given at the time of npm publish

- .changeset/six-ways-sniff.md
- src/modules/currency/getCurrencyList.ts
- src/modules/currency/types.ts
Removed redundant type from getCurrencyList API. This will also fix the below failing github action. 
After removing redundant types, Verified in definition type file, types are getting created as expected.
| JIRA link              | https://razorpay.atlassian.net/browse/ATLAS-78 |
> [fix]: redundant types deleted

- .changeset/many-zebras-sort.md
> add changeset

- .changeset/brave-dolls-kick.md
- .gitignore
- package.json
- src/modules/.internal/state/__tests__/index.test.ts
- src/modules/.internal/state/index.ts
- src/modules/.internal/state/types.ts
- src/modules/.internal/utils/__tests__/getDefaultState.test.ts
- src/modules/.internal/utils/getDefaultState.ts
- src/modules/.internal/utils/index.ts
- src/modules/core/__tests__/resetState.test.ts
- src/modules/core/index.ts
- src/modules/core/resetState.ts
- src/modules/currency/__tests__/formatNumber.test.ts
- src/modules/currency/formatNumber.ts
- src/modules/currency/formatNumberByParts.ts
Added a new API in core module to reset the i18nState. 
Also, default state changed for i18nState. 
| JIRA link              | https://razorpay.atlassian.net/browse/ATLAS-79 |
> [feat]: resetState function exposed to consumers

- .github/pull_request_template.md
This PR does following:
- Adds PR Title Format.
- Adds extra row labeled 'Fixes Issue' in 'Changes Made' Table
- Adds 'This change is a documentation update' check in 'Type of Change' section
| JIRA link              | https://razorpay.atlassian.net/browse/ATLAS-43  |
- [NA] I …
> chore: update PR Template [ATLAS-43]

- README.md
This PR adds documentation for Phone Number Module.
| JIRA link              | https://razorpay.atlassian.net/browse/ATLAS-80  |
> docs: add implementation examples for phone number module in readme [ATLAS-80]

- .changeset/dull-hounds-pretend.md
- .github/workflows/coverage.yml
- package.json
> [fix]: redundant token removed from coverage workflow

- .changeset/famous-guests-divide.md
- src/modules/.internal/utils/getLocale.ts
This PR fixes the following [issue](https://github.com/razorpay/i18nify/issues/36)
> fix : #36 corrected getLocal function.

- README.md
This PR adds the description and implementation examples of getter and setter APIs provided by the Core Module in Readme.
- README.md
| JIRA link              | https://razorpay.atlassian.net/browse/ATLAS-83  |
- [NA] Is your change backward compatible ?
- [NA] Tested on major browsers (Chrome, Firefox, Safari, IE) ?
- [NA] Tested in a consumer application(s) ?
Any additional information that …
> docs: update readme for core module

- .changeset/wild-mails-exercise.md
- packages/i18nify-js/src/modules/currency/__tests__/formatNumber.test.ts
- packages/i18nify-js/src/modules/currency/__tests__/formatNumberByParts.test.ts
- packages/i18nify-js/src/modules/currency/__tests__/getCurrencySymbol.test.ts
- packages/i18nify-js/src/modules/currency/data/currencies.ts
Removed generic `[key: string]: { symbol: string; name: string }` from CURRENCIES data. 
1. Removing this will give better typing intellisense to the consumers. 
2. Blade library also requires definite types to automatically show them in their storybook docs. 
| JIRA link              | https://razorpay.atlassian.net/browse/ATLAS-109  |
Any …
> [fix]: generic type from CURRENCIES list removed

- .gitignore
- packages/i18nify-js/scripts/bundle-size-report.js
As we introduced shared module support in this https://github.com/razorpay/i18nify/pull/66. Our bundle size report wasn't measuring the actual size of library due to multiple files. 
In this PR, I've replaced the esm file with `esm/index.min.js` as we don't follow shared module approach for this bundle. 
| JIRA link              | https://razorpay.atlassian.net/browse/ATLAS-151  |
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant …
> [fix]: bundle size report for esm/index.js replaced with esm/index.min.js

- .changeset/big-forks-deliver.md
- packages/i18nify-js/package.json
| JIRA link              | https://razorpay.atlassian.net/browse/ATLAS-152 |
| Slack thread (if any)  | https://razorpay.slack.com/archives/CMQ3RBHEU/p1708585859885849  |
---
- `fix`: (bug …
> fix: submodules added in published files in package.json

- .github/workflows/i18nify-js-danger.yml
Bundle size report for master and PR branch was coming to be same. This happened because a parameter `{{ github.base_ref }}` was mistakenly removed in this [PR](https://github.com/razorpay/i18nify/pull/53/files#diff-36baa7e5c2943f1dd604af697514a9f8364effca34e6685add8d7be354ab495fL29).
Before
After
Any additional …
> [fix]: bundle size report for master fixed

- .changeset/olive-ants-appear.md
Changeset added for this https://github.com/razorpay/i18nify/pull/106
---
- `fix`: (bug fix for the user, not a fix to a …
> [chore]: changeset added for flags unpkg

- packages/i18nify-js/README.md
- packages/i18nify-js/src/modules/geo/__tests__/getFlagOfCountry.test.ts
- packages/i18nify-js/src/modules/geo/__tests__/getFlagsForAllCountries.test.ts
- packages/i18nify-js/src/modules/geo/constants.ts
- packages/i18nify-js/src/modules/geo/getFlagOfCountry.ts
- packages/i18nify-js/src/modules/geo/getFlagsForAllCountries.ts
- packages/i18nify-js/src/modules/types/geo.ts
We utilize https://flagcdn.com/ for serving flag images to our consumers. However, since the images from this service do not follow a consistent aspect ratio, we have also included fixed aspect ratio SVGs from our own library in our delivery.
The flags are already deployed via this https://github.com/razorpay/i18nify/pull/106. Check below sample url for reference. 
https://unpkg.com/@razorpay/i18nify-js/lib/assets/flags/IN.svg
The return type of these 2 apis will change as below
1. getFlagOfCountry
```
{
"original": "https://flagcdn.com//IN.svg",
"4X3": "https://unpkg.com/@razorpay/i18nify-js/lib/assets/flags/IN.svg"
}
```
2. getFlagsForAllCountries
```
{
IN: {
"original": "https://flagcdn.com//IN.svg",
"4X3": "https://unpkg.com/@razorpay/i18nify-js/lib/assets/flags/IN.svg"
}, 
US: ...
} …
```
> [feat]: Added a new 4X3 flag from flag service

- .changeset/slow-planes-tie.md
> [chore]: changeset added

- .changeset/small-pumas-destroy.md
- packages/i18nify-js/src/modules/currency/data/currencies.ts
Included more currency codes from i18nify-data and https://www.iban.com/currency-codes. 
---
- `fix`: (bug fix for the …
> [chore]: new currency codes added

- packages/i18nify-js/README.md
> docs: Update usage docs for convertToMajorUnit and convertToMinorUnit functions

- .github/workflows/i18nify-go-ut.yml
- .github/workflows/i18nify-js-coverage.yml
Golang & JS UT check should not be triggered on master merge. Removed push condition on workflow files
---
- `fix`: (bug …
> bug:fix go & js github actions

- .changeset/wild-dryers-reply.md
- packages/i18nify-react/package.json
> [fix]: i18nify-js removed as direct dependency in i18nify-react

- .changeset/slimy-rules-thank.md
- packages/i18nify-js/src/modules/currency/__tests__/formatNumberByParts.test.ts
- packages/i18nify-js/src/modules/currency/formatNumberByParts.ts
This PR changes the logic for currency symbol placement evaluation used by formatToParts utilities.
| JIRA link              | https://razorpay.atlassian.net/browse/ATLAS-199  |
---
- `feat`: (new feature for the user, not a new …
> fix: currency symbol placement evaluation [ATLAS-199]

- i18nify-data/currency/data.json
- packages/i18nify-go/modules/currency/data.json
Fix SG currency symbol
---
- `fix`: (bug fix for the user, not a fix to a build script)
- `docs`: (changes to the …
>  bug: Fix SG currency symbol

- .github/codecov.yml
- .github/workflows/i18nify-js-coverage.yml
- packages/i18nify-js/.github/codecov.yml
- packages/i18nify-js/src/modules/currency/formatNumber.ts
> Fix: codecov coverage

- .github/workflows/i18nify-js-coverage.yml
- packages/i18nify-js/src/modules/currency/formatNumber.ts
Dorny path filter was failing in CodeCove coverage workflow when the PR got merged to master.
Failing github action
https://github.com/razorpay/i18nify/actions/runs/9265600710/job/25487985207
This PR adds a fix for same.
| JIRA link              | https://razorpay.atlassian.net/browse/ROW-144  |
Any additional information that would be helpful …
> [chore]: checkout action added in dorny path filter check

- .changeset/config.json
> fix: i18nify playground release removed from changeset

- .changeset/orange-moose-hang.md
- packages/i18nify-playground/package.json
> playground package set as private to fix changeset release

- .changeset/cold-cups-whisper.md
- packages/i18nify-js/README.md
- packages/i18nify-react/README.md
> [chore]: mock changes to trigger release

- .changeset/selfish-jars-sin.md
- packages/i18nify-js/README.md
> [chore]: mock changes for triggering release

- i18nify-data/country/subdivisions/MY.json
> Update MY Country data

- .changeset/tiny-coins-invite.md
- packages/i18nify-js/src/modules/shared/sourceConstants.ts
This PR fixes github rawcontent path which bring i18nify country data as fetch request
| JIRA link              | https://razorpay.atlassian.net/browse/ROW-561  |
---
- `feat`: (new feature for the user, not a new feature for …
> fix [ROW-561]: fix github rawcontent path

- .changeset/chilled-shoes-provide.md
> Revert "chore: add changeset for missed changes [ROW-227]"

- .github/workflows/i18nify-js-danger.yml
- .github/workflows/i18nify-js-playwright.yml
This PR updates version of actions/upload-artifact from v3 to v4 post deprecation of v3. [Details here](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/).
| JIRA link              | https://razorpay.atlassian.net/browse/ROW-735 |
---
Format: …
> chore: update actions/upload-artifact from v3 to v4 since v3 is deprecated [ROW-735]

- .github/workflows/i18nify-js-danger.yml
This PR updates version of actions/upload-artifact from v3 to v4 post deprecation of v3. [Details here](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/).
| JIRA link              | https://razorpay.atlassian.net/browse/ROW-735 |
---
Format: …
> chore: update actions/download-artifact from v3 to v4 since v3 is deprecated [ROW-735]

- packages/i18nify-playground/src/main.jsx
This PR consists fix for playground route issue when using directly `i18nify-js` as route.
---
- `fix`: (bug fix for the …
> fix: Replaced BrowserRouter with HashRouter

- packages/i18nify-playground/src/components/Dashboard/Header/Header.jsx
- packages/i18nify-playground/src/components/Dashboard/Sidebar/Sidebar.jsx
Removed the dark theme from sidebar and header of playground
---
Format: …
> feat: Remove dark theme for sidebar

- packages/i18nify-playground/index.html
NA
| JIRA link              | https://razorpay.atlassian.net/browse/ROW-735  |
---
- `fix`: (bug fix for the user, not a fix to a build script)
- `docs`: …
> docs(i18nify-playground): update meta description and improve HTML formatting [ROW-735]

- .changeset/brown-carrots-speak.md
- packages/i18nify-js/README.md
- packages/i18nify-js/src/modules/geo/__tests__/getZipcodesByCity.test.ts
- packages/i18nify-js/src/modules/geo/getZipcodesByCity.ts
- packages/i18nify-js/src/modules/geo/index.ts
Introducing a new function `getZipcodesByCity` that fetches zipcodes for a specific city within a given country. The function supports both city names and city codes, handles case insensitivity, and includes comprehensive error handling. This addition enhances the geo module by providing more granular zipcode retrieval capabilities.
| JIRA link              | https://razorpay.atlassian.net/browse/ROW-572  |
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. …
> feat: add getZipcodesByCity api in geo module [ROW-572]

- .changeset/wild-sloths-unite.md
- packages/i18nify-js/jest.config.ts
- packages/i18nify-js/src/modules/.internal/utils/__tests__/getIntlInstanceWithOptions.test.ts
- packages/i18nify-js/src/modules/currency/__tests__/formatNumber.test.ts
- packages/i18nify-js/src/modules/currency/__tests__/formatNumberByParts.test.ts
- packages/i18nify-js/src/modules/dateTime/__tests__/formatDateTime.test.ts
- packages/i18nify-js/src/modules/dateTime/__tests__/getRelativeTime.test.ts
- packages/i18nify-js/src/modules/dateTime/__tests__/getWeekdays.test.ts
- packages/i18nify-js/src/modules/dateTime/__tests__/mocks/dateFormatter.test.ts
- packages/i18nify-js/src/modules/dateTime/__tests__/mocks/dateFormatter.ts
- packages/i18nify-js/src/modules/dateTime/__tests__/parseDateTime.test.ts
- packages/i18nify-js/src/modules/dateTime/__tests__/utils.test.ts
- packages/i18nify-js/src/modules/phoneNumber/__tests__/isValidPhoneNumber.test.ts
- packages/i18nify-js/src/modules/phoneNumber/isValidPhoneNumber.ts
This PR adds missing UTs in i18nify-js modules.
| JIRA link              | https://razorpay.atlassian.net/browse/ROW-771  |
---
- `fix`: (bug fix for the …
> test: add missing UTs in i18nify-js [ROW-771]

- yarn.lock
The i18nify-react package was failing to build properly due to dependency resolution issues with @razorpay/i18nify-js/core.
- Fixed the build process by ensuring proper compilation of i18nify-js package first
- Added `--ignore-engines` flag to bypass Node.js version compatibility issues with ts-jest
- Successfully built both packages in the correct order
| JIRA link              | https://razorpay.atlassian.net/browse/ROW-792  |
Please describe the tests that you ran to verify your changes. Provide instructions so …
> fix(i18nify-react): fix build dependencies and compilation issues [ROW-792]

- packages/i18nify-go/example/example.go
- packages/i18nify-go/modules/bankcodes/bankcodes.go
- packages/i18nify-go/modules/phonenumber/phonenumber.go
- packages/i18nify-go/modules/phonenumber/phonenumber_test.go
- packages/i18nify-go/readme.md
> Updated readme, example & fix bugs using cursor/ctx

- .github/workflows/i18nify-js-coverage.yml
This PR updates the action(Setup Cache & Install Dependencies[bahmutov/npm-install@v1.10.9])'s version being used in Code coverage analysis. The current version throws
```
Error: getCacheEntry failed: Cache service responded with 503
at /home/runner/work/_actions/bahmutov/npm-install/v1.8.15/dist/index.js:51816:15
at Generator.next (<anonymous>)
at fulfilled (/home/runner/work/_actions/bahmutov/npm-install/v1.8.15/dist/index.js:51[7](https://github.com/razorpay/i18nify/actions/runs/15727324666/job/44320012698?pr=242#step:4:8)32:58)
```
| JIRA link              | https://app.devrev.ai/razorpay/works/ISS-608664  |
| Product spec           | NA …
> chore: update gh action version number for code cov
